#!/usr/bin/env node
// tokens.json is the one source of truth. Tailwind v4 (web) wants CSS @theme;
// NativeWind (mobile) wants a JS preset. Emit the CSS, hand-maintain nothing.
const fs = require('fs')
const path = require('path')
const t = require('./tokens.json')

const lines = ['/* Generated by packages/theme/build.js — edit tokens.json, not this file. */', '@theme {']
const put = (k, v) => lines.push(`  ${k}: ${v};`)

for (const [group, vals] of Object.entries(t.color)) {
  for (const [name, v] of Object.entries(vals)) {
    // surface.surface -> surface; surface.surface2 -> surface-2
    const short = name.replace(/^surface/, '') || group
    const key = group === 'surface' ? (short === group ? group : `${group}-${short}`) : `${group}-${name}`
    put(`--color-${key.replace(/([a-z])([A-Z])/g, '$1-$2').replace(/([a-z])(\d)$/, '$1-$2').toLowerCase()}`, v)
  }
}
put('--font-sans', t.font.sans)
put('--font-mono', t.font.mono)
for (const [name, v] of Object.entries(t.type)) {
  const k = name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
  put(`--text-${k}`, `${v.size}px`)
  put(`--text-${k}--line-height`, `${v.line}px`)
  put(`--text-${k}--font-weight`, v.weight)
  put(`--text-${k}--letter-spacing`, `${v.tracking ?? 0}px`)
}
for (const [name, v] of Object.entries(t.radius)) put(`--radius-${name.toLowerCase()}`, `${v}px`)
t.space.forEach((v, i) => put(`--spacing-${i + 1}`, `${v}px`))
lines.push('}')

fs.writeFileSync(path.join(__dirname, 'theme.css'), lines.join('\n') + '\n')
console.log(`theme.css: ${lines.length - 2} custom properties`)
